name: beam_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - ipykernel
  - jupyter
  - matplotlib
  - pip:
      - apache-beam[gcp]==2.61.0
      - google-cloud-storage==2.12.0